# Generated by Django 6.0.5 on 2026-06-04 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='exclusivo_melhores_amigos',
            field=models.BooleanField(default=False),
        ),
    ]
