# Generated by Django 6.0.5 on 2026-06-07 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_post_exclusivo_melhores_amigos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banido', models.BooleanField(default=False, verbose_name='Usuário Banido')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IPRegistrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco_ip', models.GenericIPAddressField(verbose_name='Endereço IP')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ips_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IP Registrado',
                'verbose_name_plural': 'IPs Registrados',
                'unique_together': {('user', 'endereco_ip')},
            },
        ),
    ]
