# Generated by Django 6.0.5 on 2026-06-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_perfilusuario_ipregistrado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo_manutencao', models.BooleanField(default=False, verbose_name='Ativar Modo Manutenção')),
                ('mensagem_manutencao', models.TextField(default='O Nexus está em manutenção para melhorias. Voltamos logo!', verbose_name='Mensagem de Aviso')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
    ]
