# Generated by Django 6.0.5 on 2026-06-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_configuracaosistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='exibir_alerta_geral',
            field=models.BooleanField(default=False, verbose_name='Exibir Alerta Geral no Topo'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='texto_alerta_geral',
            field=models.CharField(default='Aviso importante para todos os usuários!', max_length=255, verbose_name='Texto do Alerta Geral'),
        ),
    ]
