# Generated by Django 6.0.5 on 2026-06-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_configuracaosistema_exibir_alerta_geral_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaosistema',
            name='texto_alerta_geral',
            field=models.TextField(default='Aviso importante para todos os usuários!', max_length=255, verbose_name='Texto do Alerta Geral'),
        ),
    ]
