# Generated by Django 6.0.5 on 2026-06-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_alter_configuracaosistema_texto_alerta_geral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaosistema',
            name='texto_alerta_geral',
            field=models.TextField(default='Aviso importante para todos os usuários!', verbose_name='Texto do Alerta Geral'),
        ),
    ]
