# Generated by Django 6.0.5 on 2026-06-07 06:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_seguidor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='seguidor',
            old_name='alvo',
            new_name='seguido',
        ),
        migrations.AlterUniqueTogether(
            name='seguidor',
            unique_together={('seguidor', 'seguido')},
        ),
    ]
